package com;
///////////////////////////////////////////////////////////////////////////////////////////////////////
//  FILE : WebConfig.java
//  AUTHOR :  Auto-Generated by using https://start.spring.io/
//  DESCRIPTION: Used to configure CORS mappings and allowed methods/origins
//
///////////////////////////////////////////////////////////////////////////////////////////////////////

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class WebConfig implements WebMvcConfigurer {
    @Override
    public void addCorsMappings(@SuppressWarnings("null") CorsRegistry registry) {
        registry.addMapping("/**")
                .allowedOrigins("*")
                .allowedHeaders("*")
                .allowCredentials(false)
                .allowedMethods("HEAD", "GET", "PUT", "POST", "DELETE", "PATCH", "OPTIONS");
    }
}
